var annotated_dup =
[
    [ "AHTOBJ", "struct_a_h_t_o_b_j.html", "struct_a_h_t_o_b_j" ],
    [ "corCoRoutineControlBlock", "structcor_co_routine_control_block.html", "structcor_co_routine_control_block" ],
    [ "EventGroupDef_t", "struct_event_group_def__t.html", "struct_event_group_def__t" ],
    [ "HeapRegion", "struct_heap_region.html", "struct_heap_region" ],
    [ "i2c_event_status_t", "structi2c__event__status__t.html", "structi2c__event__status__t" ],
    [ "i2c_host_interface_t", "structi2c__host__interface__t.html", "structi2c__host__interface__t" ],
    [ "I2C_TRANSFER_SETUP", "struct_i2_c___t_r_a_n_s_f_e_r___s_e_t_u_p.html", "struct_i2_c___t_r_a_n_s_f_e_r___s_e_t_u_p" ],
    [ "LCDOBJ", "struct_l_c_d_o_b_j.html", "struct_l_c_d_o_b_j" ],
    [ "QueueDefinition", "struct_queue_definition.html", "struct_queue_definition" ],
    [ "QueuePointers", "struct_queue_pointers.html", "struct_queue_pointers" ],
    [ "SemaphoreData", "struct_semaphore_data.html", "struct_semaphore_data" ],
    [ "StreamBufferDef_t", "struct_stream_buffer_def__t.html", "struct_stream_buffer_def__t" ],
    [ "tskTaskControlBlock", "structtsk_task_control_block.html", "structtsk_task_control_block" ],
    [ "xEventGroupWaitBitsParams", "structx_event_group_wait_bits_params.html", "structx_event_group_wait_bits_params" ],
    [ "xHeapStats", "structx_heap_stats.html", "structx_heap_stats" ],
    [ "xLIST", "structx_l_i_s_t.html", "structx_l_i_s_t" ],
    [ "xLIST_ITEM", "structx_l_i_s_t___i_t_e_m.html", "structx_l_i_s_t___i_t_e_m" ],
    [ "xMEMORY_REGION", "structx_m_e_m_o_r_y___r_e_g_i_o_n.html", "structx_m_e_m_o_r_y___r_e_g_i_o_n" ],
    [ "xSTATIC_EVENT_GROUP", "structx_s_t_a_t_i_c___e_v_e_n_t___g_r_o_u_p.html", "structx_s_t_a_t_i_c___e_v_e_n_t___g_r_o_u_p" ],
    [ "xSTATIC_LIST", "structx_s_t_a_t_i_c___l_i_s_t.html", "structx_s_t_a_t_i_c___l_i_s_t" ],
    [ "xSTATIC_LIST_ITEM", "structx_s_t_a_t_i_c___l_i_s_t___i_t_e_m.html", "structx_s_t_a_t_i_c___l_i_s_t___i_t_e_m" ],
    [ "xSTATIC_MINI_LIST_ITEM", "structx_s_t_a_t_i_c___m_i_n_i___l_i_s_t___i_t_e_m.html", "structx_s_t_a_t_i_c___m_i_n_i___l_i_s_t___i_t_e_m" ],
    [ "xSTATIC_QUEUE", "structx_s_t_a_t_i_c___q_u_e_u_e.html", "structx_s_t_a_t_i_c___q_u_e_u_e" ],
    [ "xSTATIC_STREAM_BUFFER", "structx_s_t_a_t_i_c___s_t_r_e_a_m___b_u_f_f_e_r.html", "structx_s_t_a_t_i_c___s_t_r_e_a_m___b_u_f_f_e_r" ],
    [ "xSTATIC_TCB", "structx_s_t_a_t_i_c___t_c_b.html", "structx_s_t_a_t_i_c___t_c_b" ],
    [ "xSTATIC_TIMER", "structx_s_t_a_t_i_c___t_i_m_e_r.html", "structx_s_t_a_t_i_c___t_i_m_e_r" ],
    [ "xTASK_PARAMETERS", "structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s.html", "structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s" ],
    [ "xTASK_STATUS", "structx_t_a_s_k___s_t_a_t_u_s.html", "structx_t_a_s_k___s_t_a_t_u_s" ],
    [ "xTaskGenericNotifyParams", "structx_task_generic_notify_params.html", "structx_task_generic_notify_params" ],
    [ "xTaskGenericNotifyWaitParams", "structx_task_generic_notify_wait_params.html", "structx_task_generic_notify_wait_params" ],
    [ "xTIME_OUT", "structx_t_i_m_e___o_u_t.html", "structx_t_i_m_e___o_u_t" ],
    [ "xTimerGenericCommandFromTaskParams", "structx_timer_generic_command_from_task_params.html", "structx_timer_generic_command_from_task_params" ]
];